### ISSUE TITLE
Container does not start

### ISSUE THREAD

**Issue by coderasm** [ajacobson/chiadog-docker#1]
Every time I start a container I get a hash returned and the container never starts. I'm running the containers on a pie. I am starting one container for my farmer/node on the pie and another container for a remote harvester. Neither of them start. I see no errors in `journalctl -xb`
I use this command for the farmer:
`sudo docker run --name chiadog_farmer -d artjacobson/chiadog-docker:latest -v ~/.chiadog/farmer:/root/.chiadog -v ~/.chia/mainnet/log:/root/.chia/mainnet/log:ro -e config_dir="/root/.chiadog/config.yaml"`
and this command for the harvester:
`sudo docker run --name chiadog_harvester -d artjacobson/chiadog-docker:latest -v ~/.chiadog/harvester:/root/.chiadog -v ~/.chia/mainnet/log:/root/.chia/mainnet/log:ro -e config_dir="/root/.chiadog/config.yaml"`

**Comment by ajacobson** [comment]
Can you try launching it without the `-d` option and let me know if any errors are printed to `stdout` when attempting to run the container?

Thanks

**Comment by tedzhang2891** [comment]
I think I encounter same problem, refer to #4

**Comment by asaphaaning** [comment]
Same here.

**Comment by ajacobson** [comment]
The most likely failure scenarios would be either:
- Invalid `yaml` file
- Incorrect volume configuration

Take a look at the comments on #4, there is a suggestion that might help.  Otherwise please update this ticket with logs via either running without the `-d` flag or `docker logs <container name>`.
