### ISSUE TITLE
release 0.6.0

### ISSUE THREAD

**Issue by dvic** [ajacobson/chiadog-docker#10]
Just a friendly reminder for the 0.6.0 release:

https://github.com/martomi/chiadog/blob/429b90cf2d3f74a885d4ffcb748fb63b1521e48b/CHANGELOG.md

**Comment by ajacobson** [comment]
Already building 😃

**Comment by ajacobson** [comment]
It's now available on Docker Hub.

Don't forget to update any mounts of the Chia log directory to not be read only.  The previous instructions were read only, but that needed to change due to martomi/chiadog#164

**Comment by ajacobson** [comment]
Actually, disregard the read only thing.  There were further changes to no longer require write access to the log folder.
