### ISSUE TITLE
Unable to update from chiadog v0.3.0

### ISSUE THREAD

**Issue by stoatlemon** [ajacobson/chiadog-docker#2]
trying to update chiadog with 
`docker pull artjacobson/chiadog-docker:latest`

I get a message saying: 
`Status: Image is up to date for artjacobson/chiadog-docker:latest` 

but when I run the chiadog container it's still on 0.3.0 (not v0.4.1)

**Comment by ajacobson** [comment]
The latest tag for the Docker image has been updated to v0.4.1.

Make sure you update `config.yaml` to include the `daily_stats` section, it will crash on start without it.

**Comment by stoatlemon** [comment]
Working perfect now, Thanks!
