### ISSUE TITLE
Unable to modify container date and time to match host

### ISSUE THREAD

**Issue by dprillxyz** [ajacobson/chiadog-docker#3]
Hi,

The container does not show the same date and time as the host system. I've mounted both `/etc/timezone:/etc/timezone:ro` and `/etc/localtime:/etc/localtime:ro` to the container and the time remains UTC.

#### Output of Date from both host and container
```
~$ date && docker exec chiadog date
Sat 01 May 2021 12:37:50 PM CDT
Sat May  1 17:37:51 America 2021
~$
```

#### My Docker Compose YAML
```
# docker pull artjacobson/chiadog-docker:latest
# docker run --name <container-name> -d artjacobson/chiadog-docker:latest
# (optional -v /path/to/config_dir:/root/.chiadog -v path-to-chia-logs:/root/.chia/mainnet/log:ro)
---
version: '2.3'

services:
  chiadog:
    hostname: chiadog
    image: artjacobson/chiadog-docker:latest
    container_name: chiadog
    restart: always
    volumes:
      - /docker/chiadog:/root/.chiadog
      - /home/user/.chia/mainnet/log:/root/.chia/mainnet/log:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
```

Based on what I read on [serverfault](https://serverfault.com/questions/683605/docker-container-time-timezone-will-not-reflect-changes), one solution when using an Ubuntu base image is installing the tzdata package during build. When I tested, the tzdata package expected input during build even though you have `DEBIAN_FRONTEND=noninteractive` in your Dockerfile. When I added `ARG DEBIAN_FRONTEND="noninteractive"` above the ENV line the build went smoothly and the time inside the container matched my locally defined time zone on the host.

#### My Test Dockerfile
```
FROM ubuntu:latest

ARG DEBIAN_FRONTEND="noninteractive"

ENV config_dir=/root/.chiadog/config.yaml

RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y python3 bash ca-certificates git openssl python3-pip build-essential python3-dev python3.8-venv python3.8-distutils python-is-python3 tzdata

[no changes below here]
```

Thank you!

**Comment by ajacobson** [comment]
I added the ability to specify the timezone as an environment variable for the container: https://github.com/ajacobson/chiadog-docker/commit/2697ce3adeb036af6ad4039d28b7145b061d6385

You shouldn't need to mount `/etc/timezone` and `/etc/localtime` if you specify the `TZ` variable, but I expect that would work now that `tzdata` is being installed.
