### ISSUE TITLE
Raspberry Pi 4 (linux/arm64) compatible container

### ISSUE THREAD

**Issue by lryanuk** [ajacobson/chiadog-docker#5]
I've manually built a linux/arm64 version of this container for use on my Raspberry Pi 4 which is working well without any Dockerfile changes

Would you be able to add this OS arch to the images available in your dockerhub for others to consume without needing to build locally?

**Comment by ajacobson** [comment]
Thanks for the suggestion.

Unfortunately this doesn't look like it's a simple thing that can be edited in Docker Hub, or at least not that I can find.  There are ways to automate multi-arch builds, but it looks like I would have to change to a different build system.

I will take a look at doing that when I have some time.

**Comment by lryanuk** [comment]
I have pushed a linux/arm64 version of your container to docker hub in the meantime, hope that's OK.

https://hub.docker.com/r/lryanuk/chiadog-docker

**Comment by sbates130272** [comment]
@Iryanuk did you have issues building chiadog on arm64? It did not work for me (see https://github.com/martomi/chiadog/issues/151). I was doing this on a AWS Graviton running Ubuntu Server 20.04.

Also did you build for armhf or arm64 (i.e. did you use Po OS 32-bit or did you use a 64 bit OS?).

**Comment by lryanuk** [comment]
> @Iryanuk did you have issues building chiadog on arm64? It did not work for me (see [martomi/chiadog#151](https://github.com/martomi/chiadog/issues/151)). I was doing this on a AWS Graviton running Ubuntu Server 20.04.
> 
> Also did you build for armhf or arm64 (i.e. did you use Po OS 32-bit or did you use a 64 bit OS?).

Works OK for me, but I had installed chiadog locally before building a container so may have already have the prerequisite. 

Container is arm64, built on a Raspberry Pi 4 using 64-bit Raspbian

**Comment by sbates130272** [comment]
Thanks @lryanuk. I discovered I was missing the python3-dev package. Once I added that it all worked fine. I would love to see a docker image for Arm64!

**Comment by ajacobson** [comment]
I recently revisited this since Docker Hub shut down free autobuilds and was able to generate a multiarch build using `buildx` after a minor tweak to the `Dockerfile`.

The `latest` tag on Docker Hub should now support `linux/arm64` and `linux/amd64`
